### ISSUE TITLE
Add Clearlooks and/or Aurora engine

### ISSUE THREAD

**Issue by stil** [hexchat/gtk-win32#13]
I'd like very much to have 2 additional engines: Clearlooks and Aurora.

**Clearlooks** theme using Clearlooks engine:
![](http://i.imgur.com/JVba3jA.png)

**Aurora** theme: 
![](http://i.imgur.com/ZLacFrT.png)

**Comment by TingPing** [comment]
These engines are a part of a separate package *gtk-engines* and does not ship with gtk. The issue with this is there are absolutely no VS project files created for them and we would have to create and maintain them for functionality few would use. Anybody is free to do this themselves of course.
