### ISSUE TITLE
Move the webpage to the README file?

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#17]
So I think it is better to have the information you currently have in the webpage also in the README. The reason is that in this way you do not need to open any web page if you have the repository cloned. i.e something like:

https://github.com/nice-software/gtk-win32/commit/91e5f43901a2452fd6d56fff027d25588d3f555e

Let me know if it makes sense for you to change it and make a pull request.

**Comment by bviktor** [comment]
If you use the website, you can always have the latest info available to everyone. With an offline readme, not quite.

**Comment by nacho** [comment]
Not sure I agree on this, having all the info on the README file makes things easier when you already have the project cloned which is what you get at the end to be able to build with it. Although as said in other issue, my issues are just proposals.

**Comment by TingPing** [comment]
I think it is a bit overkill to have an entire website dedicated to a few lines for developers to build things.

A simple readme is easier to maintain and easier to find.

**Comment by Arnavion** [comment]
So move the content to the README and have https://hexchat.github.io/gtk-win32/ redirect to https://github.com/hexchat/gtk-win32/blob/master/README.md then?

**Comment by nacho** [comment]
I'd simply remove the web page and just maintain the README?
