### ISSUE TITLE
Drop mozilla-build

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#19]
Right now I think we use mozilla-build just for a few things that it provides. mozilla-build also uses msys which is kind of deprecated right now. Instead we should probably use msys2

**Comment by bviktor** [comment]
The good thing about mozilla-build that it bundles a bunch of useful utils into a single installer. You don't have to download several packages. And as long as it works, I fail to see the reason to drop mozilla-build. Especially since we only use it for build time, not for run time.

**Comment by Arnavion** [comment]
For reference, MB is used for:

- patch.exe for all deps
- cl.exe wrappers for libffi

We put a bunch of other stuff in the MB directory that could be placed elsewhere instead:
- nasm for openssl
- perl for openssl and HC
- python for HC

**Comment by nzjrs** [comment]
I removed the dependence on MB. You can see that commit here https://github.com/nice-software/gtk-win32/commit/6d1928e23c4d44ea31ef48093fb0f2ddf7e226ba

**Comment by nacho** [comment]
cool!

On Sat, Mar 7, 2015 at 9:41 AM, John Stowers <notifications@github.com>
wrote:

> I removed the dependence on MB. You can see that commit here
> nice-software@6d1928e
> <https://github.com/nice-software/gtk-win32/commit/6d1928e23c4d44ea31ef48093fb0f2ddf7e226ba>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexchat/gtk-win32/issues/19#issuecomment-77679796>.
>



-- 
Ignacio Casal Quinteiro

**Comment by nacho** [comment]
@Arnavion what do you think should we try to get this in hexchat directly?

**Comment by nacho** [comment]
Another interesting thing now that it is using msys2 is to drop 7zip and use instead the tools provided by msys2. tar, xz, 7zip itself etc

**Comment by nzjrs** [comment]
We could add a pre-build step that checks/installs those things. By piping ```pacman -S bla``` into the msys2 shell.

**Comment by Arnavion** [comment]
If you're still going to use m-b's VS shell for libffi, I don't see the point of not depending on it...

**Comment by nzjrs** [comment]
I have msys2 installed for building and distributing my software on windows, I thought it was better to use that than whatever old copy mozilla ships.

Futhermore, I use appveyor to build other software, so making this build system less dependent on mozilla build means I can run this against their standard build image (which incidentally uses mingw vanilla) and keep under the 40 min build limit.

**Comment by Arnavion** [comment]
>(and I copied the m-b build shell into tree, in case you missed it)

That is exactly why I said you still depend on it.

>I thought it was better to use that than whatever old copy mozilla ships.

Is there an actual technical reason for this other than architectural purity? Is there anything where the few parts of msys we use that are broken and would be fixed by msys2?

**Comment by nzjrs** [comment]
Actually, that depends on what you consider a valid technical reason. For me, keeping the appveyor build time under 40 minutes is a valid technical reason.

I have't had to implement the ssh-add killing thing, so maybe that is a problem related to m-b? Or maybe I just have not hit it yet.

**Comment by Arnavion** [comment]
[libffi is built with VS now,](https://github.com/hexchat/gtk-win32/commit/554fcfe) so we can now drop the m-b dependency.

**Comment by nzjrs** [comment]
@Arnavion thanks a lot!

**Comment by Arnavion** [comment]
https://github.com/hexchat/gtk-win32/commit/f4bb600

I haven't removed all the uses for 7z yet.

**Comment by nacho** [comment]
@Arnavion thanks a lot for your work on this. We will definitely rebase our repo too with your changes.

**Comment by Arnavion** [comment]
BTW, I thought of using msgfmt from msys2's gettext package, but it throws some warnings about the translation files in GTK and @TingPing isn't sure whether they matter or not. So for now msgfmt continues to be a separate requirement.

```
<Arnavion> So, it's 0.19.4-1 instead of whatever we have
<Arnavion> and it prints one error for each .po in glib:   gtk : zh_TW.po:7: warning: header field 'Language' missing in header
<Arnavion> Is it fine?
<TingPing> not sure
```

**Comment by nacho** [comment]
that kind of warning should be fine, is though the Language filed in the po file?

**Comment by nacho** [comment]
strange, so the language field seems to be there, https://git.gnome.org/browse/glib/tree/po/zh_TW.po#n18

**Comment by nacho** [comment]
Hi, Is there any reason to put as default msys32 instead of msys64? The recommended one by the msys guys is usually the 64 bit version.

**Comment by Arnavion** [comment]
Only that 32-bit msys works for both 32-bit OS and 64-bit OS, so I didn't see the need to complicate the instructions. Also, they recommend the 64-bit version only because there's no point to using the 32-bit version on 64-bit OS, not because the 64-bit version is different in any functional way.

**Comment by nacho** [comment]
I actually thought the 32 bit version would not provide the 64 mingw?

**Comment by Arnavion** [comment]
Both the mingw32 and mingw64 directories are empty, if that's what you mean. What of it?

**Comment by nacho** [comment]
Yeah, it seems that it is just a matter of optimization.

**Comment by Arnavion** [comment]
Regarding the Language header, I meant gtk, not glib (the error message was correct). GTK master files have the header but not in 2.24:   https://github.com/GNOME/gtk/blob/gtk-2-24/po/zh_TW.po#L8-L17

**Comment by nacho** [comment]
@Arnavion should we then just use msgfmt from msys2?

**Comment by Arnavion** [comment]
https://github.com/hexchat/gtk-win32/issues/19#issuecomment-83054973

**Comment by nacho** [comment]
@Arnavion sure but if it produces a warning that is correct shouldn't we switch to it?

**Comment by Arnavion** [comment]
>@TingPing isn't sure whether they matter or not

Tool A doesn't give a warning - it might be a real issue but tool A's output is evidently usable, so it's seemingly okay to use.

Tool B gives a warning - there is no guarantee that tool B's output is usable.

Fix the missing header in gtk 2.24 so that the warning goes away and then I can look into using 0.19.4 for the build as well. Alternatively convince me that the warning can be ignored.

**Comment by nacho** [comment]
I can definitely tell you that it is a warning that can be ignored. (talking as ex gtranslator maintainer :P)

**Comment by nacho** [comment]
in any case I'll just fix it upstream as well.

**Comment by nacho** [comment]
Done: https://git.gnome.org/browse/gtk+/commit/?h=gtk-2-24&id=a4bffe01bb78e6088ce787be71bf79e9cd080818

**Comment by TingPing** [comment]
> Done: https://git.gnome.org/browse/gtk+/commit/?h=gtk-2-24&id=a4bffe01bb78e6088ce787be71bf79e9cd080818

All po files do not have it.

**Comment by nacho** [comment]
strange, I wonder if it was removed for some reason

**Comment by nacho** [comment]
mmm, i.e gl has it https://git.gnome.org/browse/gtk+/tree/po/gl.po?h=gtk-2-24#n32
