### ISSUE TITLE
Update glib to 2.44

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#25]
So the new stable released was just released. I guess it is a good time to start checking if it builds fine and whether we need some patch upstream

**Comment by Arnavion** [comment]
Keep this in the tracking issue.

**Comment by nacho** [comment]
In case you are interested here is the patch we have in our repo: https://github.com/nice-software/gtk-win32/commit/8b76823f1bc20aa2a93555b5b4ee77abb2e49539
