### ISSUE TITLE
Fatal error when using GTK bundle to build my program

### ISSUE THREAD

**Issue by Adriatic1** [hexchat/gtk-win32#26]
When using the GTK build provided by this project, I get a following compiler error:

```
7>d:\program files\microsoft visual studio 12.0\vc\include\xkeycheck.h(203): warning C4005: 'inline' : macro redefinition
7>          c:\gtk\include\libintl.h(23) : see previous definition of 'inline'
7>d:\program files\microsoft visual studio 12.0\vc\include\xkeycheck.h(250): fatal error C1189: #error :  The C++ Standard Library forbids macroizing keywords. Enable warning C4005 to find the forbidden macro.
```

The solution is to remove/comment following lines at the top of the libintl.h file:

```c
#ifdef _MSC_VER
#define inline __inline
#endif
```

The compiler I use is VS 2013 Community edition.

**Comment by Arnavion** [comment]
Change your code to compile in C mode, not C++

**Comment by Adriatic1** [comment]
OK, I see you don't want to fix anything beyond your narrow scope of use.
My program is C++ program with 250k lines, so it is not practical that i make a rewrite per your suggestion.
This was the only issue i encountered with this stack, so I wouldn't know of other headers.

**Comment by TingPing** [comment]
@Adriatic1 You could always send the patch he mentioned upstream.

**Comment by Arnavion** [comment]
I did not tell you to change your entire 250k line C++ program to C. I told you to change the code that includes the header to C.

**Comment by Adriatic1** [comment]
Changing the code that includes that would in turn require the need to patch gtkspell for example.
My experience is that this was the first GTK build for windows that caused the issues with C++ code, but perhaps this one uses latest code so this is a recent issue.

**Comment by Arnavion** [comment]
>Changing the code that includes that would in turn require the need to patch gtkspell for example.

No it would not, since gtkspell is also a C library.

**Comment by Adriatic1** [comment]
OK, this discussion definitely seem pointless, since you are not interested in fixing even such a trivial fix, and I already fixed it for myself.
Let me just say that I have been building Windows builds of my C++ program since 2004, and in these years I've tried at least 3 GTK stack builds other than yours (using official build while Tor was maintaining them for example), and I never had such type of issue.
This does not imply that you should fix anything, but for me as a potential user of this stack build it is a bad sign you are not willing to fix even trivial issues like this one.

**Comment by Arnavion** [comment]
In case you didn't notice, this repository is primarily a build script. It fetches source code from upstream and builds it. If you want something fixed, do what TingPing told you to and submit the fix to the proper place, not here. It is not my issue to fix.

Now if it was only one header to patch, I would've been amenable to accomodate you and add a patch for it. But there are many such headers. I'm not going to add a patch for each and every one of them, then have to deal with updating them every time a new release comes out and the patch no longer applies.

Trying to guilt me into increasing my patch burden for you, or trying to impress me that you have a C++ program that you created in 2004, or displaying your pompous entitlement that I should fix other people's bugs for you, is not going to get you anywhere. If another GTK2 stack satisfies you, feel free to use it. If you want to maintain your own patch that deletes 3 lines from the header in this stack, feel free to do that.

This repository is maintained by HexChat devs, and so we only care to make it work for HexChat, which among other things is a C application. This is detailed in the issue TingPing already linked you to.

**Comment by Adriatic1** [comment]
As I said before, this sounds pretty pointless. Let's drop this, we all know that nothing interesting will happen here for both sides.
