### ISSUE TITLE
Add gtksourceview 2.x in the build script

### ISSUE THREAD

**Issue by Adriatic1** [hexchat/gtk-win32#27]
If possible, please add support to build gtksourceview 2.x in this project,

I assume it is not so much work for you and a lot of people would benefit from this, so you would get more exposure and testing of the GTK stack you provide.
Perhaps in the future, even hexchat could benefit by using this widget (autocompletion, line numbers, syntax highlighting, ...)

**Comment by TingPing** [comment]
>Perhaps in the future, even hexchat could benefit by using this widget (autocompletion, line numbers, syntax highlighting, ...)

Except HexChat is not an editor...

See #24 about some discussion on including projects not used by HexChat.
