### ISSUE TITLE
A way to specify additional compiler/linker settings 

### ISSUE THREAD

**Issue by FictionIO** [hexchat/gtk-win32#28]
Hi,

I'am trying to build libraries with /MT flag. Is there a way to build with this type of specific settings? I tried to do it manually with text search&replace to cloned hexchat/gtk-win32 repo didn't help. If there is im happy to update readme instructions to include such a route.

**Comment by Arnavion** [comment]
All projects already set `RuntimeLibrary` to `MultiThreadedDLL`

**Comment by Arnavion** [comment]
And if you specifically meant to compile with the multi-threaded *static* CRT, then you'll have to replace that property in every project.

**Comment by FictionIO** [comment]
Correct me if im wrong /MT is Multithreaded (what i want) MultiThreadedDLL is /MD (not what i want). So at the moment its /MD no /MT

**Comment by FictionIO** [comment]
@Arnavion There is no /MD or anything to replace with /MT and still if your suggestion works its not documented.

**Comment by Arnavion** [comment]
I already told you you need to change the RuntimeLibrary property in each project file.

And of course it's documented. https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vcprojectengine.vcclcompilertool.runtimelibrary tells you it's an enum, which itself is at https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vcprojectengine.runtimelibraryoption
