### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#31]
Hey guys, just wanted to concrete what kind of license the project has. If the same as hexchat I guess we should add the COPYING file to it.

**Comment by Arnavion** [comment]
It's implicitly GPL (individual GPL libraries + modified project files = derivative work). The repo-specific stuff like the build script are also GPL for the same reason.

But yes it should be made explicit with a license file.

**Comment by nacho** [comment]
Sounds good, but this is not so implicit since i.e openssl uses a different license.

**Comment by Arnavion** [comment]
openssl license does not affect the rest of the repo. It is a separate component that resides in the same repo - it is not linked or related to the rest (gtk and its deps) in any way.

**Comment by Arnavion** [comment]
Discussion continues in the PR.
