### ISSUE TITLE
Update win-iconv and gettext-runtime build scripts

### ISSUE THREAD

**Issue by ghost** [hexchat/gtk-win32#7]
Now they generate makefiles during a GTK+ build. Generate solutions instead, modify them according to our build practices and add them to the repo.

This also means CMake won't be required for a GTK+ rebuild, only for win-iconv and gettext-runtime bumps (very rare).

**Comment by Arnavion** [comment]
If upstream uses CMake then there's no pressing need for us to check in the generated solutions.
